//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Escaperoom_2.Application.Assets.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Backend_Escaperoom_2.Application.Assets.Resources.Languages.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wi-fi Access.
        /// </summary>
        public static string AccesoWifi {
            get {
                return ResourceManager.GetString("AccesoWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Farm.
        /// </summary>
        public static string ActualizarFinca {
            get {
                return ResourceManager.GetString("ActualizarFinca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update weighing session.
        /// </summary>
        public static string ActualizarSesionPesaje {
            get {
                return ResourceManager.GetString("ActualizarSesionPesaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administration.
        /// </summary>
        public static string Administracion {
            get {
                return ResourceManager.GetString("Administracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to reset the animal&apos;s weight history with code:.
        /// </summary>
        public static string AdvAnimalHistorial {
            get {
                return ResourceManager.GetString("AdvAnimalHistorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string Advertencia {
            get {
                return ResourceManager.GetString("Advertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning!.
        /// </summary>
        public static string AdvertenciaAlert {
            get {
                return ResourceManager.GetString("AdvertenciaAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weight was updated.
        /// </summary>
        public static string AnimalActualizoPeso {
            get {
                return ResourceManager.GetString("AnimalActualizoPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a &apos;Code&apos; or &apos;Identification&apos; for the animal..
        /// </summary>
        public static string AnimalCodigo {
            get {
                return ResourceManager.GetString("AnimalCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is no animal data to delete..
        /// </summary>
        public static string AnimalDelete {
            get {
                return ResourceManager.GetString("AnimalDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No animals have been removed..
        /// </summary>
        public static string AnimalesNoEliminados {
            get {
                return ResourceManager.GetString("AnimalesNoEliminados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select one or more &apos;Animals&apos;..
        /// </summary>
        public static string AnimalesSelected {
            get {
                return ResourceManager.GetString("AnimalesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a gender for the &apos;Animal&apos;..
        /// </summary>
        public static string AnimalGeneroSelect {
            get {
                return ResourceManager.GetString("AnimalGeneroSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The observation must be between 3 to 50 characters..
        /// </summary>
        public static string AnimalObservacionLenght {
            get {
                return ResourceManager.GetString("AnimalObservacionLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter an &apos;Observation&apos; for the animal..
        /// </summary>
        public static string AnimalObservacionNullEmpty {
            get {
                return ResourceManager.GetString("AnimalObservacionNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weighed animal without checking zero (0.0)..
        /// </summary>
        public static string AnimalPesadoSinVer {
            get {
                return ResourceManager.GetString("AnimalPesadoSinVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Very high &apos;Weight of the Animal&apos;..
        /// </summary>
        public static string AnimalPesoAlto {
            get {
                return ResourceManager.GetString("AnimalPesoAlto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Very low &apos;Animal Weight&apos;..
        /// </summary>
        public static string AnimalPesoBajo {
            get {
                return ResourceManager.GetString("AnimalPesoBajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Animal&apos; is already heavy:.
        /// </summary>
        public static string AnimalReemplazado {
            get {
                return ResourceManager.GetString("AnimalReemplazado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Replaced animal.
        /// </summary>
        public static string AnimalReemplazadoObs {
            get {
                return ResourceManager.GetString("AnimalReemplazadoObs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The weight history has been reset successfully, the next weigh-in will be reflected in gain and performance..
        /// </summary>
        public static string AnimalReinicioExitoso {
            get {
                return ResourceManager.GetString("AnimalReinicioExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Years.
        /// </summary>
        public static string Años {
            get {
                return ResourceManager.GetString("Años", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Surnames&apos; must be between 5 to 30 characters..
        /// </summary>
        public static string ApellidosLenght {
            get {
                return ResourceManager.GetString("ApellidosLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your &apos;Surname&apos;..
        /// </summary>
        public static string ApellidosNullEmpty {
            get {
                return ResourceManager.GetString("ApellidosNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Automatic.
        /// </summary>
        public static string Automatico {
            get {
                return ResourceManager.GetString("Automatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        public static string Ayuda {
            get {
                return ResourceManager.GetString("Ayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Character, Allowed Characters:.
        /// </summary>
        public static string CaracterInvalid {
            get {
                return ResourceManager.GetString("CaracterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading....
        /// </summary>
        public static string Cargando {
            get {
                return ResourceManager.GetString("Cargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Cell Number&apos; is Incorrect..
        /// </summary>
        public static string CelularIncorrect {
            get {
                return ResourceManager.GetString("CelularIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your &apos;Cell Number&apos;..
        /// </summary>
        public static string CelularNull {
            get {
                return ResourceManager.GetString("CelularNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        public static string CerrarSesion {
            get {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;Confirm password&apos; must be between 8 to 20 characters..
        /// </summary>
        public static string ChangedConfirmNewPassLength {
            get {
                return ResourceManager.GetString("ChangedConfirmNewPassLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm your new &apos;Password&apos;..
        /// </summary>
        public static string ChangedConfirmNewPassNull {
            get {
                return ResourceManager.GetString("ChangedConfirmNewPassNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The new &apos;Passwords&apos; are not the same..
        /// </summary>
        public static string ChangedNewPassEquals {
            get {
                return ResourceManager.GetString("ChangedNewPassEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your new &apos;Password&apos; must be between 8 to 20 characters..
        /// </summary>
        public static string ChangedNewPassLenght {
            get {
                return ResourceManager.GetString("ChangedNewPassLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your new &apos;Password&apos;..
        /// </summary>
        public static string ChangedNewPassNull {
            get {
                return ResourceManager.GetString("ChangedNewPassNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your &apos;Password&apos; above must be between 8 to 20 characters..
        /// </summary>
        public static string ChangedOldPassLenght {
            get {
                return ResourceManager.GetString("ChangedOldPassLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your &apos;Password&apos; above..
        /// </summary>
        public static string ChangedOldPassNull {
            get {
                return ResourceManager.GetString("ChangedOldPassNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your password has been changed..
        /// </summary>
        public static string ChangedPassword {
            get {
                return ResourceManager.GetString("ChangedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advanced configuration.
        /// </summary>
        public static string ConfigAvanzada {
            get {
                return ResourceManager.GetString("ConfigAvanzada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicator settings.
        /// </summary>
        public static string ConfigIndicador {
            get {
                return ResourceManager.GetString("ConfigIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The last saved configuration is loaded..
        /// </summary>
        public static string ConfigIndUltSave {
            get {
                return ResourceManager.GetString("ConfigIndUltSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string Configuracion {
            get {
                return ResourceManager.GetString("Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General settings.
        /// </summary>
        public static string ConfiguracionGeneral {
            get {
                return ResourceManager.GetString("ConfiguracionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thank you for registering at &apos;Livestock Control of Prometálicos S.A&apos;. You only have one more step to activate your account..
        /// </summary>
        public static string ConfirmEmailBody1 {
            get {
                return ResourceManager.GetString("ConfirmEmailBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please click the following link to confirm the email.
        /// </summary>
        public static string ConfirmEmailBody2 {
            get {
                return ResourceManager.GetString("ConfirmEmailBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Now you can log..
        /// </summary>
        public static string ConfirmEmailIniciarSesion {
            get {
                return ResourceManager.GetString("ConfirmEmailIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please confirm your email address.
        /// </summary>
        public static string ConfirmEmailSubject {
            get {
                return ResourceManager.GetString("ConfirmEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm your email address.
        /// </summary>
        public static string ConfirmEmailTittle {
            get {
                return ResourceManager.GetString("ConfirmEmailTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account confirmed for.
        /// </summary>
        public static string ConfirmEmailUser {
            get {
                return ResourceManager.GetString("ConfirmEmailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm &apos;Password&apos; must be 8 to 20 characters..
        /// </summary>
        public static string ConfirmPassLenght {
            get {
                return ResourceManager.GetString("ConfirmPassLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm the &apos;Password&apos;..
        /// </summary>
        public static string ConfirmPassNullEmpty {
            get {
                return ResourceManager.GetString("ConfirmPassNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consult Animal.
        /// </summary>
        public static string ConsultarAnimal {
            get {
                return ResourceManager.GetString("ConsultarAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        public static string Continuar {
            get {
                return ResourceManager.GetString("Continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Livestock control.
        /// </summary>
        public static string ControlGanadero {
            get {
                return ResourceManager.GetString("ControlGanadero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data updated successfully..
        /// </summary>
        public static string DatosActualizados {
            get {
                return ResourceManager.GetString("DatosActualizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data deleted successfully..
        /// </summary>
        public static string DatosEliminados {
            get {
                return ResourceManager.GetString("DatosEliminados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data saved successfully..
        /// </summary>
        public static string DatosGuardados {
            get {
                return ResourceManager.GetString("DatosGuardados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your personal information does not exist..
        /// </summary>
        public static string DatosPersonalesNoExist {
            get {
                return ResourceManager.GetString("DatosPersonalesNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Personal Data&apos; are not yours..
        /// </summary>
        public static string DatosPersonalesNoPropio {
            get {
                return ResourceManager.GetString("DatosPersonalesNoPropio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;State&apos; does not exist..
        /// </summary>
        public static string DepNoExist {
            get {
                return ResourceManager.GetString("DepNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Do you want to replace it?.
        /// </summary>
        public static string DeseaReemplazarlo {
            get {
                return ResourceManager.GetString("DeseaReemplazarlo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Destination&apos; of the dispatch must have between 5 to 25 characters..
        /// </summary>
        public static string DespachoDestinoLeght {
            get {
                return ResourceManager.GetString("DespachoDestinoLeght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a &apos;Destination&apos; of the office..
        /// </summary>
        public static string DespachoDestinoNull {
            get {
                return ResourceManager.GetString("DespachoDestinoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Customer Name&apos; must be between 10 to 30 characters..
        /// </summary>
        public static string DespachoNomClienteLeght {
            get {
                return ResourceManager.GetString("DespachoNomClienteLeght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the &apos;Customer Name&apos;..
        /// </summary>
        public static string DespachoNomClienteNull {
            get {
                return ResourceManager.GetString("DespachoNomClienteNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a &apos;Number of Vehicles&apos; for dispatch..
        /// </summary>
        public static string DespachoNumVehiculosNull {
            get {
                return ResourceManager.GetString("DespachoNumVehiculosNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the &apos;Name of the person in charge&apos; of the transport..
        /// </summary>
        public static string DespachoResponsableNull {
            get {
                return ResourceManager.GetString("DespachoResponsableNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the &apos;Responsible Name&apos; must have between 10 to 25 characters..
        /// </summary>
        public static string DespachoResposableLeght {
            get {
                return ResourceManager.GetString("DespachoResposableLeght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Farm details.
        /// </summary>
        public static string DetallesFinca {
            get {
                return ResourceManager.GetString("DetallesFinca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Device&apos; must not exceed 30 characters..
        /// </summary>
        public static string DipositivoDeviceLenght {
            get {
                return ResourceManager.GetString("DipositivoDeviceLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The device &apos;Manufacturer&apos; must not exceed 20 characters..
        /// </summary>
        public static string DispositivoFabricante {
            get {
                return ResourceManager.GetString("DispositivoFabricante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The decive &apos;Model&apos; must not exceed 30 characters..
        /// </summary>
        public static string DispositivoModelo {
            get {
                return ResourceManager.GetString("DispositivoModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Device&apos; does not exist..
        /// </summary>
        public static string DispositivoNoExist {
            get {
                return ResourceManager.GetString("DispositivoNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The device &apos;Name&apos; must not exceed 30 characters..
        /// </summary>
        public static string DispositivoNombre {
            get {
                return ResourceManager.GetString("DispositivoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Device information is required..
        /// </summary>
        public static string DispositivoNull {
            get {
                return ResourceManager.GetString("DispositivoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The device &apos;Platform&apos; must not exceed 20 characters..
        /// </summary>
        public static string DispositivoPlataforma {
            get {
                return ResourceManager.GetString("DispositivoPlataforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The device &apos;OS Version&apos; must NOT exceed 10 characters..
        /// </summary>
        public static string DispositivoVersion {
            get {
                return ResourceManager.GetString("DispositivoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove.
        /// </summary>
        public static string Elimina {
            get {
                return ResourceManager.GetString("Elimina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Email&apos; is wrong..
        /// </summary>
        public static string EmailIncorrecto {
            get {
                return ResourceManager.GetString("EmailIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the &apos;Email&apos;..
        /// </summary>
        public static string EmailNullEmpty {
            get {
                return ResourceManager.GetString("EmailNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Email&apos; is already in use..
        /// </summary>
        public static string EmailUse {
            get {
                return ResourceManager.GetString("EmailUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Error!.
        /// </summary>
        public static string ErrorAlert {
            get {
                return ResourceManager.GetString("ErrorAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is not possible to update the weight of the animal, because there is a traceability with the weight in one or more weighing sessions..
        /// </summary>
        public static string ErrorAnimalTrazabilidad {
            get {
                return ResourceManager.GetString("ErrorAnimalTrazabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The weighing history cannot be reset, because there is traceability with the weight in one or more weighing sessions..
        /// </summary>
        public static string ErrorAnimalTrazabilidad2 {
            get {
                return ResourceManager.GetString("ErrorAnimalTrazabilidad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The indicator is at (0.0), please validate if there is weight on the scale..
        /// </summary>
        public static string ErrorCeroGN {
            get {
                return ResourceManager.GetString("ErrorCeroGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error connecting to the device, check the connection with the weight indicator and try again..
        /// </summary>
        public static string ErrorConectIndicador {
            get {
                return ResourceManager.GetString("ErrorConectIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while confirming the email.
        /// </summary>
        public static string ErrorConfirmEmail {
            get {
                return ResourceManager.GetString("ErrorConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The device is not connected to any network, check your connection..
        /// </summary>
        public static string ErrorConInternet {
            get {
                return ResourceManager.GetString("ErrorConInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error trying to extract device information..
        /// </summary>
        public static string ErrorDispositivo {
            get {
                return ResourceManager.GetString("ErrorDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to save information..
        /// </summary>
        public static string ErrorGuardar {
            get {
                return ResourceManager.GetString("ErrorGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred in the request..
        /// </summary>
        public static string ErrorHttp {
            get {
                return ResourceManager.GetString("ErrorHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;License&apos; is linked to another indicator..
        /// </summary>
        public static string ErrorIndicadorLicencia {
            get {
                return ResourceManager.GetString("ErrorIndicadorLicencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error releasing the weight from the indicator..
        /// </summary>
        public static string ErrorLiberarInd {
            get {
                return ResourceManager.GetString("ErrorLiberarInd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error during the login process..
        /// </summary>
        public static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Parameterization error!.
        /// </summary>
        public static string ErrorParametrizacion {
            get {
                return ResourceManager.GetString("ErrorParametrizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It was not possible to validate the zero crossing of the indicator..
        /// </summary>
        public static string ErrorPasoCeroInd {
            get {
                return ResourceManager.GetString("ErrorPasoCeroInd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred during the registration process..
        /// </summary>
        public static string ErrorRegistroUser {
            get {
                return ResourceManager.GetString("ErrorRegistroUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while resetting the password..
        /// </summary>
        public static string ErrorRestablecerPass {
            get {
                return ResourceManager.GetString("ErrorRestablecerPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Synchronization error..
        /// </summary>
        public static string ErrorSincronizacion {
            get {
                return ResourceManager.GetString("ErrorSincronizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while saving the information, please check all the fields..
        /// </summary>
        public static string ErrorUpdateConfigInd {
            get {
                return ResourceManager.GetString("ErrorUpdateConfigInd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One or more validation errors have occurred..
        /// </summary>
        public static string ErrorValidation {
            get {
                return ResourceManager.GetString("ErrorValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to delete.
        /// </summary>
        public static string EstaSeguroDelete {
            get {
                return ResourceManager.GetString("EstaSeguroDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want.
        /// </summary>
        public static string EstasSeguro {
            get {
                return ResourceManager.GetString("EstasSeguro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Events.
        /// </summary>
        public static string Eventos {
            get {
                return ResourceManager.GetString("Eventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is already a farm with this name:.
        /// </summary>
        public static string ExistFinca {
            get {
                return ResourceManager.GetString("ExistFinca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User session has expired.
        /// </summary>
        public static string ExpiredSesionUser {
            get {
                return ResourceManager.GetString("ExpiredSesionUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing.
        /// </summary>
        public static string Faltan {
            get {
                return ResourceManager.GetString("Faltan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Date of birth&apos; must be greater than the year 1900..
        /// </summary>
        public static string FechaNaciMayor {
            get {
                return ResourceManager.GetString("FechaNaciMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;birth date&apos; must be less than the current date..
        /// </summary>
        public static string FechaNaciMenor {
            get {
                return ResourceManager.GetString("FechaNaciMenor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select your &apos;Date of birth&apos;..
        /// </summary>
        public static string FechaNaciNullEmpty {
            get {
                return ResourceManager.GetString("FechaNaciNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The farm.
        /// </summary>
        public static string Finca {
            get {
                return ResourceManager.GetString("Finca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Active.
        /// </summary>
        public static string FincaActiva {
            get {
                return ResourceManager.GetString("FincaActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect &apos;Cell phone&apos; number..
        /// </summary>
        public static string FincaCelularIncorrect {
            get {
                return ResourceManager.GetString("FincaCelularIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a &apos;Cell phone&apos; number..
        /// </summary>
        public static string FincaCelularNull {
            get {
                return ResourceManager.GetString("FincaCelularNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a &apos;State&apos;..
        /// </summary>
        public static string FincaDepartamentoNull {
            get {
                return ResourceManager.GetString("FincaDepartamentoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Address must be between 10 to 30 characters..
        /// </summary>
        public static string FincaDireccionLenght {
            get {
                return ResourceManager.GetString("FincaDireccionLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the &apos;Address&apos; of the farm..
        /// </summary>
        public static string FincaDireccionNull {
            get {
                return ResourceManager.GetString("FincaDireccionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inactive.
        /// </summary>
        public static string FincaInactiva {
            get {
                return ResourceManager.GetString("FincaInactiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To update the information, you must first activate the farm..
        /// </summary>
        public static string FincaInactiva2 {
            get {
                return ResourceManager.GetString("FincaInactiva2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a &apos;City&apos;..
        /// </summary>
        public static string FincaMunicipioNull {
            get {
                return ResourceManager.GetString("FincaMunicipioNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Name&apos; must be between 3 to 30 characters..
        /// </summary>
        public static string FincaNombreLenght {
            get {
                return ResourceManager.GetString("FincaNombreLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a &apos;Name&apos; for the farm..
        /// </summary>
        public static string FincaNombreNullEmpty {
            get {
                return ResourceManager.GetString("FincaNombreNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Farms.
        /// </summary>
        public static string Fincas {
            get {
                return ResourceManager.GetString("Fincas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect &apos;Phone&apos; number..
        /// </summary>
        public static string FincaTelefonoIncorrect {
            get {
                return ResourceManager.GetString("FincaTelefonoIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I see you&apos;ve forgotten your password for your account..
        /// </summary>
        public static string ForgotPassBody1 {
            get {
                return ResourceManager.GetString("ForgotPassBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please click the following link to reset your password.
        /// </summary>
        public static string ForgotPassBody2 {
            get {
                return ResourceManager.GetString("ForgotPassBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password reset successful..
        /// </summary>
        public static string ForgotPassChanged {
            get {
                return ResourceManager.GetString("ForgotPassChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instructions to retrieve your password have been emailed..
        /// </summary>
        public static string ForgotPassConfirmApi {
            get {
                return ResourceManager.GetString("ForgotPassConfirmApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your &apos;Email&apos; to search for your account..
        /// </summary>
        public static string ForgotPassEmailNullEmpty {
            get {
                return ResourceManager.GetString("ForgotPassEmailNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover password.
        /// </summary>
        public static string ForgotPassTittle {
            get {
                return ResourceManager.GetString("ForgotPassTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Forgot your password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset password.
        /// </summary>
        public static string ForgotpPassSubject {
            get {
                return ResourceManager.GetString("ForgotpPassSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gain.
        /// </summary>
        public static string Ganancia {
            get {
                return ResourceManager.GetString("Ganancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select your &apos;Gender&apos;..
        /// </summary>
        public static string GeneroNullEmpty {
            get {
                return ResourceManager.GetString("GeneroNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Female.
        /// </summary>
        public static string Hembra {
            get {
                return ResourceManager.GetString("Hembra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hi.
        /// </summary>
        public static string Hola {
            get {
                return ResourceManager.GetString("Hola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a &apos;Number of users&apos; that can link to the weight indicator..
        /// </summary>
        public static string IndicadoNumUsersNull {
            get {
                return ResourceManager.GetString("IndicadoNumUsersNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The weight &apos;Indicator&apos; has already been assigned to another user..
        /// </summary>
        public static string IndicadorAssignament {
            get {
                return ResourceManager.GetString("IndicadorAssignament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to load the default configuration for the weight indicator with serial:.
        /// </summary>
        public static string IndicadorConfigPred {
            get {
                return ResourceManager.GetString("IndicadorConfigPred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The weight &apos;Indicator&apos; is already registered..
        /// </summary>
        public static string IndicadorExist {
            get {
                return ResourceManager.GetString("IndicadorExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Model&apos; of the indicator must not exceed 15 characters..
        /// </summary>
        public static string IndicadorModeloLenght {
            get {
                return ResourceManager.GetString("IndicadorModeloLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the &apos;Model&apos; of the indicator..
        /// </summary>
        public static string IndicadorModeloNull {
            get {
                return ResourceManager.GetString("IndicadorModeloNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The indicator is out of (0.0), press the &apos;ZERO&apos; key on the weight indicator and try again..
        /// </summary>
        public static string IndicadorNegativo {
            get {
                return ResourceManager.GetString("IndicadorNegativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If the problem continues, reset the weight indicator..
        /// </summary>
        public static string IndicadorNegativo2 {
            get {
                return ResourceManager.GetString("IndicadorNegativo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The weight &apos;Indicator&apos; is not active..
        /// </summary>
        public static string IndicadorNoActivo {
            get {
                return ResourceManager.GetString("IndicadorNoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The weight &apos;Indicator&apos; does not exist..
        /// </summary>
        public static string IndicadorNoExist {
            get {
                return ResourceManager.GetString("IndicadorNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Number of users&apos; must be greater than zero..
        /// </summary>
        public static string IndicadorNumUsersCero {
            get {
                return ResourceManager.GetString("IndicadorNumUsersCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Number of users&apos; must be less than fifty..
        /// </summary>
        public static string IndicadorNumUsersMenor {
            get {
                return ResourceManager.GetString("IndicadorNumUsersMenor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weight indicator.
        /// </summary>
        public static string IndicadorPeso {
            get {
                return ResourceManager.GetString("IndicadorPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The weight indicator is busy at the average weight..
        /// </summary>
        public static string IndicadorPromedio {
            get {
                return ResourceManager.GetString("IndicadorPromedio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to select the indicator with S/N:.
        /// </summary>
        public static string IndicadorSelectQuestion {
            get {
                return ResourceManager.GetString("IndicadorSelectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Serial&apos; must be between 5 to 20 characters..
        /// </summary>
        public static string IndicadorSerialLenght {
            get {
                return ResourceManager.GetString("IndicadorSerialLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the &apos;Serial&apos; of the indicator..
        /// </summary>
        public static string IndicadorSerialNull {
            get {
                return ResourceManager.GetString("IndicadorSerialNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It has been synced successfully..
        /// </summary>
        public static string IndicadorSincronizado {
            get {
                return ResourceManager.GetString("IndicadorSincronizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected Indicator is not synchronized..
        /// </summary>
        public static string IndicadorSinVerificar {
            get {
                return ResourceManager.GetString("IndicadorSinVerificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Version&apos; of the indicator must not exceed 10 characters..
        /// </summary>
        public static string IndicadorVersionLenght {
            get {
                return ResourceManager.GetString("IndicadorVersionLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the &apos;Version&apos; of the indicator..
        /// </summary>
        public static string IndicadorVersionNull {
            get {
                return ResourceManager.GetString("IndicadorVersionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wireless network name, wireless network password, ip address, port and more ....
        /// </summary>
        public static string IndoComunicacionDescrip {
            get {
                return ResourceManager.GetString("IndoComunicacionDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Communication information.
        /// </summary>
        public static string InfoComunicacion {
            get {
                return ResourceManager.GetString("InfoComunicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advanced settings.
        /// </summary>
        public static string InfoConfigAvanzada {
            get {
                return ResourceManager.GetString("InfoConfigAvanzada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Negative weights, zero crossing, release weight, zero button and more ....
        /// </summary>
        public static string InfoConfigAvanzadaDescrip {
            get {
                return ResourceManager.GetString("InfoConfigAvanzadaDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicator information.
        /// </summary>
        public static string InfoIndicador {
            get {
                return ResourceManager.GetString("InfoIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serial, model, version and more ....
        /// </summary>
        public static string InfoIndicadorDescrip {
            get {
                return ResourceManager.GetString("InfoIndicadorDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        public static string Informacion {
            get {
                return ResourceManager.GetString("Informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weight tolerances.
        /// </summary>
        public static string InfoTolerancias {
            get {
                return ResourceManager.GetString("InfoTolerancias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimum weight tolerance, maximum weight tolerance and more ....
        /// </summary>
        public static string InfoToleranciasDescrip {
            get {
                return ResourceManager.GetString("InfoToleranciasDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the.
        /// </summary>
        public static string IngresaLos {
            get {
                return ResourceManager.GetString("IngresaLos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter.
        /// </summary>
        public static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Destination on the farm&apos; of the income must be between 5 to 30 characters..
        /// </summary>
        public static string IngresoDestinoLeght {
            get {
                return ResourceManager.GetString("IngresoDestinoLeght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the &apos;Destination in the farm&apos; of the income..
        /// </summary>
        public static string IngresoDestinoNullEmpty {
            get {
                return ResourceManager.GetString("IngresoDestinoNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the &apos;Origin&apos; of the income..
        /// </summary>
        public static string IngresoProcedenciaNullEmpty {
            get {
                return ResourceManager.GetString("IngresoProcedenciaNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Origin&apos; of the entry must be between 5 to 30 characters..
        /// </summary>
        public static string IngresoProdecenciaLeght {
            get {
                return ResourceManager.GetString("IngresoProdecenciaLeght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logging in....
        /// </summary>
        public static string IniciandoSesion {
            get {
                return ResourceManager.GetString("IniciandoSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licencie.
        /// </summary>
        public static string Licencia {
            get {
                return ResourceManager.GetString("Licencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;License&apos; has expired, please contact.
        /// </summary>
        public static string LicenciaExpire {
            get {
                return ResourceManager.GetString("LicenciaExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the &apos;Expiration time&apos; of the License..
        /// </summary>
        public static string LicenciaExpireTime {
            get {
                return ResourceManager.GetString("LicenciaExpireTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a &apos;Number&apos; of allowed weight indicators..
        /// </summary>
        public static string LicenciaIndicadorPer {
            get {
                return ResourceManager.GetString("LicenciaIndicadorPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a &apos;Weight Indicator&apos;..
        /// </summary>
        public static string LicenciaIndicadorPeso {
            get {
                return ResourceManager.GetString("LicenciaIndicadorPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Number&apos; of weight indicators must be greater than zero (0)..
        /// </summary>
        public static string LicenciaIndicadorZero {
            get {
                return ResourceManager.GetString("LicenciaIndicadorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;License&apos; must be 29 characters long..
        /// </summary>
        public static string LicenciaLenght {
            get {
                return ResourceManager.GetString("LicenciaLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;License&apos; has reached the limit of registered users..
        /// </summary>
        public static string LicenciaLimit {
            get {
                return ResourceManager.GetString("LicenciaLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;License&apos; is not active..
        /// </summary>
        public static string LicenciaNoActiva {
            get {
                return ResourceManager.GetString("LicenciaNoActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;License&apos; does not exist..
        /// </summary>
        public static string LicenciaNoExist {
            get {
                return ResourceManager.GetString("LicenciaNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the &apos;License&apos;..
        /// </summary>
        public static string LicenciaNullEmpty {
            get {
                return ResourceManager.GetString("LicenciaNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a &apos;Number&apos; of allowed users..
        /// </summary>
        public static string LicenciaNumUsersPermitidos {
            get {
                return ResourceManager.GetString("LicenciaNumUsersPermitidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Number&apos; of allowed users must be greater than zero (0)..
        /// </summary>
        public static string LicenciaNumUsersZero {
            get {
                return ResourceManager.GetString("LicenciaNumUsersZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Observations&apos; must not exceed 50 characters..
        /// </summary>
        public static string LicenciaObsLenght {
            get {
                return ResourceManager.GetString("LicenciaObsLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remember, once logged in, you cannot log into another device..
        /// </summary>
        public static string LoginDispositivoMovil {
            get {
                return ResourceManager.GetString("LoginDispositivoMovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The current &apos;Device&apos; has another user assigned. Please contact your administrator..
        /// </summary>
        public static string LoginDispositivoNoUser {
            get {
                return ResourceManager.GetString("LoginDispositivoNoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The User has not confirmed the &apos;Email&apos;..
        /// </summary>
        public static string LoginEmailConfim {
            get {
                return ResourceManager.GetString("LoginEmailConfim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must confirm the email address, the confirmation has been sent to your email again..
        /// </summary>
        public static string LoginEmailConfim2 {
            get {
                return ResourceManager.GetString("LoginEmailConfim2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Email&apos; does not exist..
        /// </summary>
        public static string LoginEmailNoExist {
            get {
                return ResourceManager.GetString("LoginEmailNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;License&apos; does not belong to this user..
        /// </summary>
        public static string LoginLicenciaNoUser {
            get {
                return ResourceManager.GetString("LoginLicenciaNoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are logged on your mobile correctly..
        /// </summary>
        public static string LoginMobileReady {
            get {
                return ResourceManager.GetString("LoginMobileReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;Password&apos; is incorrect..
        /// </summary>
        public static string LoginPassIncorrect {
            get {
                return ResourceManager.GetString("LoginPassIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have successfully logged in..
        /// </summary>
        public static string LoginReady {
            get {
                return ResourceManager.GetString("LoginReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to logout?.
        /// </summary>
        public static string LogoutPregunta {
            get {
                return ResourceManager.GetString("LogoutPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Male.
        /// </summary>
        public static string Macho {
            get {
                return ResourceManager.GetString("Macho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manual.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User manual.
        /// </summary>
        public static string ManualUsuario {
            get {
                return ResourceManager.GetString("ManualUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Months.
        /// </summary>
        public static string Meses {
            get {
                return ResourceManager.GetString("Meses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a &apos;City&apos;..
        /// </summary>
        public static string MunicipioNull {
            get {
                return ResourceManager.GetString("MunicipioNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;City&apos; does not exist..
        /// </summary>
        public static string MunNoExist {
            get {
                return ResourceManager.GetString("MunNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your &apos;Names&apos;..
        /// </summary>
        public static string NombreNullEmpty {
            get {
                return ResourceManager.GetString("NombreNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Names&apos; must be between 3 to 30 characters..
        /// </summary>
        public static string NombresLenght {
            get {
                return ResourceManager.GetString("NombresLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New weighing session.
        /// </summary>
        public static string NuevaSesionPesaje {
            get {
                return ResourceManager.GetString("NuevaSesionPesaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manual weight.
        /// </summary>
        public static string ObsPesoManual {
            get {
                return ResourceManager.GetString("ObsPesoManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Country&apos; does not exist..
        /// </summary>
        public static string PaisNoExist {
            get {
                return ResourceManager.GetString("PaisNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Password&apos; must be between 8 to 20 characters..
        /// </summary>
        public static string PassLenght {
            get {
                return ResourceManager.GetString("PassLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Passwords&apos; are not the same..
        /// </summary>
        public static string PassNoEquals {
            get {
                return ResourceManager.GetString("PassNoEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the &apos;Password&apos;..
        /// </summary>
        public static string PassNullEmpty {
            get {
                return ResourceManager.GetString("PassNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loss.
        /// </summary>
        public static string Perdida {
            get {
                return ResourceManager.GetString("Perdida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privacy.
        /// </summary>
        public static string Politica {
            get {
                return ResourceManager.GetString("Politica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Question?.
        /// </summary>
        public static string Pregunta {
            get {
                return ResourceManager.GetString("Pregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿What do you want to do?.
        /// </summary>
        public static string QueDeseasHacer {
            get {
                return ResourceManager.GetString("QueDeseasHacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prometálicos S.A.
        /// </summary>
        public static string RazonSocial {
            get {
                return ResourceManager.GetString("RazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remember me?.
        /// </summary>
        public static string Recuerdame {
            get {
                return ResourceManager.GetString("Recuerdame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register Farm.
        /// </summary>
        public static string RegistrarFinca {
            get {
                return ResourceManager.GetString("RegistrarFinca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign up.
        /// </summary>
        public static string Registrarme {
            get {
                return ResourceManager.GetString("Registrarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please restart the weight indicator to display the changes..
        /// </summary>
        public static string ResetIndicador {
            get {
                return ResourceManager.GetString("ResetIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to reset advanced settings?.
        /// </summary>
        public static string RestablecerConfigAvan {
            get {
                return ResourceManager.GetString("RestablecerConfigAvan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to reset the general settings?.
        /// </summary>
        public static string RestablecerConfigGeneral {
            get {
                return ResourceManager.GetString("RestablecerConfigGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to reset the default tolerances?.
        /// </summary>
        public static string RestablecerTol {
            get {
                return ResourceManager.GetString("RestablecerTol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset password.
        /// </summary>
        public static string RestorePassword {
            get {
                return ResourceManager.GetString("RestorePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select one or more &apos;Farms&apos;.
        /// </summary>
        public static string SelectFinca {
            get {
                return ResourceManager.GetString("SelectFinca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opened.
        /// </summary>
        public static string SesionAbierta {
            get {
                return ResourceManager.GetString("SesionAbierta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Closed.
        /// </summary>
        public static string SesionCerrada {
            get {
                return ResourceManager.GetString("SesionCerrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weighing session.
        /// </summary>
        public static string SesionDePeso {
            get {
                return ResourceManager.GetString("SesionDePeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weighing session dispatch.
        /// </summary>
        public static string SesionDespachar {
            get {
                return ResourceManager.GetString("SesionDespachar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weight Sessions.
        /// </summary>
        public static string SesionesPeso {
            get {
                return ResourceManager.GetString("SesionesPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a &apos;Farm&apos;..
        /// </summary>
        public static string SesionFinca {
            get {
                return ResourceManager.GetString("SesionFinca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weighing session income.
        /// </summary>
        public static string SesionIngresar {
            get {
                return ResourceManager.GetString("SesionIngresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a name for the &apos;Lot&apos;..
        /// </summary>
        public static string SesionLote {
            get {
                return ResourceManager.GetString("SesionLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the name of the &apos;Weigher&apos;..
        /// </summary>
        public static string SesionNomPesador {
            get {
                return ResourceManager.GetString("SesionNomPesador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The weigher&apos;s name must be 10 to 25 characters long..
        /// </summary>
        public static string SesionNomPesadorLenght {
            get {
                return ResourceManager.GetString("SesionNomPesadorLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to close the weighing session as an internal control?.
        /// </summary>
        public static string SesionPesajeClosedC {
            get {
                return ResourceManager.GetString("SesionPesajeClosedC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is not possible to close the session, an animal must weigh..
        /// </summary>
        public static string SesionPesajeVacia {
            get {
                return ResourceManager.GetString("SesionPesajeVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a price per Kilogram..
        /// </summary>
        public static string SesionPrecioKg {
            get {
                return ResourceManager.GetString("SesionPrecioKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Must be greater than 0.
        /// </summary>
        public static string SesionPrecioKg2 {
            get {
                return ResourceManager.GetString("SesionPrecioKg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the &apos;Type of weighing session&apos;..
        /// </summary>
        public static string SesionTipo {
            get {
                return ResourceManager.GetString("SesionTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Note&apos; must be between 5 to 100 characters..
        /// </summary>
        public static string SessionNota {
            get {
                return ResourceManager.GetString("SessionNota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Phone Number&apos; is Incorrect..
        /// </summary>
        public static string TelefonoIncorrect {
            get {
                return ResourceManager.GetString("TelefonoIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Land.
        /// </summary>
        public static string Terrestre {
            get {
                return ResourceManager.GetString("Terrestre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The response time has expired. Please check your connection and try again..
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicator response time expired..
        /// </summary>
        public static string TimeOutIndicador {
            get {
                return ResourceManager.GetString("TimeOutIndicador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control.
        /// </summary>
        public static string TipoSesionControl {
            get {
                return ResourceManager.GetString("TipoSesionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispatch.
        /// </summary>
        public static string TipoSesionDespacho {
            get {
                return ResourceManager.GetString("TipoSesionDespacho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Income.
        /// </summary>
        public static string TipoSesionIngreso {
            get {
                return ResourceManager.GetString("TipoSesionIngreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The role or user type does not exist..
        /// </summary>
        public static string TipoUsuarioNull {
            get {
                return ResourceManager.GetString("TipoUsuarioNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Email.
        /// </summary>
        public static string TitleConfirmEmail {
            get {
                return ResourceManager.GetString("TitleConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string TitleEmail {
            get {
                return ResourceManager.GetString("TitleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm new password.
        /// </summary>
        public static string TitleNewPassConfirm {
            get {
                return ResourceManager.GetString("TitleNewPassConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string TitleNewPassword {
            get {
                return ResourceManager.GetString("TitleNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset your password.
        /// </summary>
        public static string TitleResetPassword {
            get {
                return ResourceManager.GetString("TitleResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Token&apos; has been modified..
        /// </summary>
        public static string TokenNullEmpty {
            get {
                return ResourceManager.GetString("TokenNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You do not have the permissions to access this resource..
        /// </summary>
        public static string TokenOnForbidden {
            get {
                return ResourceManager.GetString("TokenOnForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must be logged in to access this resource..
        /// </summary>
        public static string TokenUnauthorized {
            get {
                return ResourceManager.GetString("TokenUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tolerances Weight.
        /// </summary>
        public static string ToleranciaPeso {
            get {
                return ResourceManager.GetString("ToleranciaPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video Tutorial.
        /// </summary>
        public static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User created successfully..
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;User&apos; is inactive or disabled..
        /// </summary>
        public static string UserNoActivo {
            get {
                return ResourceManager.GetString("UserNoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registered user, Before logging in you must confirm the email..
        /// </summary>
        public static string UserRegisterConfirmApi {
            get {
                return ResourceManager.GetString("UserRegisterConfirmApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;User&apos; does not exist..
        /// </summary>
        public static string UsuarioNoExiste {
            get {
                return ResourceManager.GetString("UsuarioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Guide Number&apos; must be between 3 to 25 characters..
        /// </summary>
        public static string ValNumeroGuia {
            get {
                return ResourceManager.GetString("ValNumeroGuia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle.
        /// </summary>
        public static string Vehiculo {
            get {
                return ResourceManager.GetString("Vehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a animals to be assigned to a vehicle..
        /// </summary>
        public static string VehiculoAsignar {
            get {
                return ResourceManager.GetString("VehiculoAsignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Driver Name&apos; must be between 10 to 25 characters long..
        /// </summary>
        public static string VehiculoNomConductorLenght {
            get {
                return ResourceManager.GetString("VehiculoNomConductorLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the &apos;Driver&apos;s name&apos;..
        /// </summary>
        public static string VehiculoNomConductorNull {
            get {
                return ResourceManager.GetString("VehiculoNomConductorNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;Badge&apos; must be 6 characters long..
        /// </summary>
        public static string VehiculoPlacaLenght {
            get {
                return ResourceManager.GetString("VehiculoPlacaLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a &apos;License Plate&apos; for the vehicle..
        /// </summary>
        public static string VehiculoPlacaNull {
            get {
                return ResourceManager.GetString("VehiculoPlacaNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicles.
        /// </summary>
        public static string Vehiculos {
            get {
                return ResourceManager.GetString("Vehiculos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The number of vehicles is &apos;0&apos; or it is a negative number, enter a correct value..
        /// </summary>
        public static string VehiculosCero {
            get {
                return ResourceManager.GetString("VehiculosCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximum of vehicles entered..
        /// </summary>
        public static string VehiculosMaximos {
            get {
                return ResourceManager.GetString("VehiculosMaximos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a remaining vehicles..
        /// </summary>
        public static string VehiculosRestantes {
            get {
                return ResourceManager.GetString("VehiculosRestantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select one or more &apos;Vehicles&apos;..
        /// </summary>
        public static string VehiculosSeleccionar {
            get {
                return ResourceManager.GetString("VehiculosSeleccionar", resourceCulture);
            }
        }
    }
}
